### ISSUE TITLE
Is it possible to add/change the includemodel

### ISSUE THREAD

**Issue by HotoCocoaco** [arthurdead/animhelpers#1]
Allow model to read sequences from other animation model.

**Comment by arthurdead** [comment]
animations are client-side the server only tells the client which number to play
even if you somehow hacked a new includedmodel in the server the client wouldnt know about it

that being said if the skeleton structures of the 2 models are the same just use bonemerge
or if the skeleton structures are different you can use prop_posable: https://github.com/arthurdead/sm-plugins/blob/master/addons/sourcemod/scripting/prop_posable.sp
and make your own bonemerge code from scratch
